name: mindsdb
version: latest
summary: A snap fo mindsdb
description: |
  Mindsdb
base: core18
confinement: devmode


parts:
  test-offlineimap:
    plugin: python
    python-version: python3
    python-packages:
      - mindsdb

apps:
  start-mindsdb:
    command: bin/mindsdb
