tasks:
  - name: Setup mindsdb development environment
    init: |
      pip install -U pip
      pip install -r requirements.txt
      pip install -r requirements-dev.txt
      python setup.py develop
    command: |
      python -m mindsdb
