# This starts databases for local development or integration tests as if they were launched locally.
# Run `docker-compose up -d`
# Shut down and clean up: `docker-compose down`
version: "3"
services:
  mariadb:
    build: .
    image: mariadb-connect:1
    container_name: connect
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - ./connectData:/var/lib/mysql
    - ./connect.cnf:/etc/mysql/mariadb.conf.d/connect.cnf
  clickhouse:
    image: yandex/clickhouse-server:20.1
    ports:
      - 8123:8123
