site_name: MindsDB Documentation
site_url: 'https://docs.mindsdb.com'
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  custom_dir: overrides
  logo: assets/mdb_logo_w.svg
  favicon: assets/mdb_logo.png
  font:
      text: Inter
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
    - redirects:
        redirect_maps:
            'installation/Installing.md': 'index.md'
            'Installing.md': 'index.md'
            'databases/tutorials/AiTablesInPostgreSQL': 'tutorials/postgresql.md'
            'databases/tutorials/AiTablesInMySQL': 'tutorials/mysql.md'
            'databases/MariaDB': 'tutorials/mariadb.md'
            'installation/Linux/': '/deployment/linux.md'
            'installation/Windows/': '/deployment/windows.md'
            'installation/MacOS/': '/deployment/macos.md'
            'installation/macos/': '/deployment/macos.md'
            'installation/linux/': '/deployment/linux.md'
    - table-reader
markdown_extensions:
  - attr_list
  - md_in_html
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables

nav:
  - Quickstart: index.md
  - What is MindsDB?: what-is-mindsdb.md
  - Setup:
    - Self-hosted:
      - Docker: setup/self-hosted/docker.md
      - pip:
        - Windows via pip: setup/self-hosted/pip/windows.md
        - Linux via pip: setup/self-hosted/pip/linux.md
        - MacOs via pip: setup/self-hosted/pip/macos.md
        - Sourcecode via pip: setup/self-hosted/pip/source.md
    - MindsDB Cloud: setup/cloud.md
  - Connect:
      - MySQL CLI: connect/mysql-client.md
      - MindsDB Cloud Editor: connect/mindsdb_editor.md
      - DBeaver: connect/dbeaver.md
      - Deepnote: connect/deepnote.md
      - SQL Alchemy: connect/sql-alchemy.md
      - DBT: connect/dbt.md
      - Kafka: connect/kafka.md 
      - Tableau: connect/tableau.md
  - SQL API:
    - Table Structure (Schema): sql/table-structure.md
    - CREATE:
      - Database: sql/create/databases.md
      - Predictor: sql/create/predictor.md
      - View: sql/create/view.md
    - DESCRIBE: sql/api/describe.md
    - RETRAIN: sql/api/retrain.md
    - DROP: sql/api/drop.md
    - SELECT: sql/api/select.md
    - SELECT from files: sql/api/select_files.md
    - JOIN: sql/api/join.md
  - Using a custom model:
    - MLFlow: custom-model/mlflow.md
    - Ray Serve: custom-model/ray-serve.md
    - HuggingFace: custom-model/huggingface.md
    - OpenAi: custom-model/openai.md

  - Tutorials:
    - Regression:
      - Process Quality: tutorials/regression/process-quality.md
      - Body Fat Prediction: tutorials/regression/bodyfat.md
    - Classification:
      - Customer Churn: tutorials/classification/customer-churn.md
      - Heart Disease: tutorials/classification/heart-disease.md
      - Mushrooms Hunting: tutorials/classification/mushrooms.md
    - Time Series:
      - AI powered forecasts with MindsDB: tutorials/time-series/mindsdb-superset-snowflake.md
  - Community Tutorials:
    - Regression:
      - Insurance Cost: sql/tutorials/insurance-cost-prediction.md
    - Classification:
      - Crop Recommendation: sql/tutorials/crop-prediction.md
      - Diabetes: sql/tutorials/diabetes.md  
  - Contribution and Community:
      - How to contribute: contribute.md
      - Join our community: community.md
extra_css:
  - stylesheets/extra.css