site_name: MindsDB Documentation
site_url: 'https://docs.mindsdb.com'
repo_name: 'mindsdb/mindsdb'
repo_url: 'https://github.com/mindsdb/mindsdb'
theme:
  name: 'material'
  custom_dir: overrides
  logo: assets/mdb_logo_w.svg
  favicon: assets/mdb_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
    - search:
        lang: 'en'
        social:
          - type: 'github'
            link: 'https://github.com/mindsdb/mindsdb'
          - type: 'twitter'
            link: 'https://twitter.com/mindsdb'
          - type: 'link'
            link: 'https://www.mindsdb.com'
    - redirects:
        redirect_maps:
            'installation/Installing.md': 'index.md'
            'Installing.md': 'index.md'
            'databases/tutorials/AiTablesInPostgreSQL': 'tutorials/postgresql.md'
            'databases/tutorials/AiTablesInMySQL': 'tutorials/mysql.md'
            'databases/MariaDB': 'tutorials/mariadb.md'
            'installation/Linux/': '/deployment/linux.md'
            'installation/Windows/': '/deployment/windows.md'
            'installation/MacOS/': '/deployment/macos.md'
            'installation/macos/': '/deployment/macos.md'
            'installation/linux/': '/deployment/linux.md'
    - table-reader
    - i18n:
        default_language: en
        languages:
          en: English
          zh: Chinese

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
nav:
  - What is MindsDB: index.md
  - Getting Started Guide:
    - Getting Started: info.md
    - Docker: deployment/docker.md
    - Pip: deployment/pypi.md
    - MindsDB Cloud: deployment/cloud.md
  - Plug your data: connect.md
  - Connect to MindsDB SQL Server:
      - Local Deployment: sql/connect/local.md
      - MindsDB Cloud: sql/connect/cloud.md
  - SQL:
    - USE: sql/api/use.md
    - CREATE:
      - Predictor: sql/api/predictor.md
      - View: sql/api/view.md
      - USING: sql/api/using.md
    - RETRAIN: sql/api/retrain.md
    - DROP: sql/api/drop.md
    - SELECT: sql/api/select.md
    - SELECT from FILES: sql/api/SELECT_Files.md
    - JOIN: sql/api/join.md
  - Tutorials:
    - Bring Your Own Model: sql/tutorials/byom.md
    - AI Tables Intro: sql/tutorials/ai-tables.md
    - Regression:
      - Process Quality: sql/tutorials/process-quality.md
      - Body Fat Prediction: sql/tutorials/bodyfat.md
      - Insurance Cost: sql/tutorials/insurance-cost-prediction.md
    - Classification:
      - Crop Recommendation: sql/tutorials/crop-prediction.md
      - Customer Churn: sql/tutorials/customer-churn.md
      - Diabetes: sql/tutorials/diabetes.md
      - Heart Disease: sql/tutorials/heart-disease.md
      - Mushrooms: sql/tutorials/mushrooms.md
    - Time series:
      - AI powered forecasts with MindsDB: sql/tutorials/mindsdb-superset-snowflake.md
  - Contribution and Community:
      - How to contribute: contribute.md
      - Join our community: community.md
      - FAQ: faq.md
extra_css:
  - stylesheets/extra.css