name: 🐞 Report a bug
description: Create a bug report to help us improve MindsDB
title: "[Bug]: "
labels: [bug]
body:

- type: textarea
  attributes:
    label: Current Behavior
    description: A short description of what you're experiencing
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Video or screenshots
    description: The better the evidence you can provide, the faster we can fix it!
    placeholder: https://www.loom.com/share/abcdefghijklmnopqrrstuvwxyz
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Expected Behavior
    description: A short description of what you expected to happen.
  validations:
    required: false
   
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: The better the evidence you can provide, the faster we can fix it!
    placeholder: |
      I uses these queries...
      I was running MindsDB on...
      I get this error...
  validations:
    required: false
   
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Ideas? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
