# This starts databases for local development or integration tests as if they were launched locally.
# Run `docker-compose up -d`
# Shut down and clean up: `docker-compose down`

# Comment out any databases you don't want to run.

version: "3"

services:
  mindsdb:
    image: mindsdb/mindsdb:latest
    container_name: mindsdb_mindsdb
    command: bash -c "pip install --no-cache-dir mindsdb; python3 -m mindsdb"
    ports:
      - 47334:47334

  mariadb:
    build: mariadb/.
    container_name: mindsdb_mariadb
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - ${PWD}/mariadb/storage:/var/lib/mysql
    - ${PWD}/mariadb/connect.cnf:/etc/mysql/mariadb.conf.d/connect.cnf

  clickhouse:
    image: yandex/clickhouse-server:20.1
    container_name: mindsdb_clickhouse
    volumes:
      - ${PWD}/clickhouse/storage:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000

  mysql:
    network_mode: host
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mindsdb_mysql
    volumes:
    - ${PWD}/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    - ${PWD}/mysql/storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3307:3307

  postgres:
    build: postgres/.
    network_mode: host
    container_name: mindsdb_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
    - ${PWD}/postgres/storage:/var/lib/postgresql/data
    - ${PWD}/postgres/share:/share