package:
    name: mindsdb
    version: "2.10.2"

source:
    git_url: https://github.com/mindsdb/mindsdb.git
    git_rev: "v2.10.2"

extra:
    channels:
        - conda-forge
    deploy:
        - anaconda-client

build:
    noarch: python
    entry-points:
        - mindsb = mindsdb.__main__:main

    script:
        python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    host:
        - python
        - pip
    build:
        - yaml
    run:
        - python>=3.5

dependencies:
        - pip:
            - mindsdb_native == 2.13.0
            - flask-restx >= 0.2.0
            - flask >= 1.0
            - python-multipart >= 0.0.5
            - moz-sql-parser == 3.32.20026
            - pyparsing == 2.3.1
            - cryptography >= 2.9.2
            - pg8000 >= 1.15.3
            - python-tds >= 1.10.0
            - flask_cors >= 1.1
            - waitress >= 1.4.4
            - pymongo >= 3.10.1
            - setuptools
            - psutil

about:
    home: "git@github.com:mindsdb/mindsdb.git"
    license: "GPL-3.0"
    # description:  maintainers and contributors
